routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([],function(){
	Route::get('eglise.log', 'HomeController@log')->name('eglise.log');
	Route::get('android', 'HomeController@download')->name('apk');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::group(['middleware'=>'auth:eglise', 'namespace'=>'Admin'], function(){

	Route::get('/', 'AdminController@index');
	Route::resource('groupe', 'GroupeController');
	Route::resource('annonce', 'AnnonceController');
	Route::put('annonce.state/{id}', 'AnnonceController@changeState')->name('annonce.state');
});

Route::group(['namespace'=>'Admin'], function(){
	Route::post('admin/log', 'AdminController@logAdmin')->name('admin.log');
});

Route::group(['middleware'=>'auth', 'namespace'=>'Admin'], function(){
		Route::get('admin', 'AdminController@index')->name('admin.index');
	  Route::resource('eglise', 'EgliseController');
});

Route::group(['middleware'=>'auth'], function(){
	Route::resource('district', 'District\DistrictController');
});

Route::resource('users', 'Users\UsersController');

Route::resource('roles', 'Users\RolesController');

Route::resource('permissions', 'Users\PermissionsController');

app/Http/Controllers/Users/RolesController.php
<?php

namespace App\Http\Controllers\Users;

use \Auth;
use \Session;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RolesController extends Controller
{

    public function __construct() {
        //$this->middleware(['auth', 'isAdmin']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        
        $roles = Role::all();//Get all roles

        return view('admin.roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        
        $permissions = Permission::all();//Get all permissions

        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
    //Validate name and permissions field
        $this->validate($request, [
            'name'=>'required|unique:roles|max:14',
            'permissions' =>'required',
            ]
        );

        $name = $request['name'];
        
        $role = Role::create($request->only('name'));

        $permissions = $request['permissions'];

        //Looping thru selected permissions
        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); 
         //Fetch the newly created role and assign permission
            $role->givePermissionTo($p);
        }

        return redirect()->route('admin.roles.index')
            ->with('flash_message',
             'Role'. $role->name.' added!'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect('roles');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();

        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $role = Role::findOrFail($id);//Get role with the given id
    //Validate name and permission fields
        $this->validate($request, [
            'name'=>'required|max:14|unique:roles,name,'.$id,
            'permissions' =>'required',
        ]);

        $input = $request->except(['permissions']);
        $permissions = $request['permissions'];
        $role->fill($input)->save();

        $p_all = Permission::all();//Get all permissions

        foreach ($p_all as $p) {
            $role->revokePermissionTo($p); //Remove all permissions associated with role
        }

        foreach ($permissions as $permission) {
            $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
            $role->givePermissionTo($p);  //Assign permission to role
        }

        return redirect()->route('admin.roles.index')
            ->with('flash_message',
             'Role'. $role->name.' updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id)->delete();
        
        return response()->json();
    }

}

resources/views/admin/roles/create.blade.php
@extends('layouts.app')

@section('main')
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="#">Home</a></li>                    
        <li class="active">Roles</li>
    </ul>
    <!-- END BREADCRUMB --> 
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            @component('components.card-form', ['route' => route('annonce.store')])

                @slot('titre')
                    @lang('Creation de role')
                @endslot

                @section('champs')
                    {{ csrf_field() }}            
                    @include('partials.form-group', [
                        'title' => __('Penser de la semaine'),
                        'type' => 'text',
                        'name' => 'pense',
                        'required' => true,
                        ])
                    @include('partials.hidden', [
                        'value' => 'annonce',
                        ])
                @overwrite
            @endcomponent
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Role')

@section('content')
<div class="row">
    <div class="offset-md-3 mt-4 col-md-6">
        <!-- Horizontal Form -->
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title"><i class='fa fa-key'></i> Edit Role: {{$role->name}}</h3>
            </div>
            <div class="card-body">
                {{ Form::model($role, array('route' => array('roles.update', $role->id), 'method' => 'PUT')) }}

                <div class="form-group">
                    {{ Form::label('name', 'Role Name') }}
                    {{ Form::text('name', null, array('class' => 'form-control')) }}
                </div>

                <h5><b>Assign Permissions</b></h5>
                @foreach ($permissions as $permission)

                    {{Form::checkbox('permissions[]',  $permission->id, $role->permissions ) }}
                    {{Form::label($permission->name, ucfirst($permission->name)) }}<br>

                @endforeach
                <br>
                {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}    
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/roles/index.blade.php
{{-- \resources\views\roles\index.blade.php --}}
@extends('layouts.app')

@section('main')
<!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="#">Home</a></li>                    
        <li class="active">Dashboard</li>
    </ul>
<!-- END BREADCRUMB -->                     
<!-- START WIDGETS -->   

<div class="col-lg-8 col-lg-offset-2 mb-5">
    <h1><i class="fa fa-key"></i> Roles

    <a href="{{ route('users.index') }}" class="btn btn-default pull-right">Users</a>
    <a href="{{ route('permissions.index') }}" class="btn btn-default pull-right">Permissions</a></h1>
    <hr>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Data Table With Full Features</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example2" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Role</th>
                        <th>Permissions</th>
                        <th>Operation</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($roles as $role)
                    <tr>

                        <td>{{ $role->name }}</td>

                        <td>{{ str_replace(array('[',']','"'),'', $role->permissions()->pluck('name')) }}</td>{{-- Retrieve array of permissions associated to a role and convert to string --}}
                        <td>
                        <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-info btn-sm pull-left mr-3 invisible" title="@lang('Modifier utilisateur') {{$role->name}}"><i class="fa fa-edit"></i> edite</a>
                        <a href="{{ route('roles.destroy', $role->id) }}" class="btn btn-danger btn-sm invisible" title="@lang('Supprimer ulitisateur') {{$role->name}}">
                            <i class="fa fa-trash fa-lg"></i> supprime</a>   

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <a href="{{ URL::to('roles/create') }}" class="btn btn-success">Add Role</a>

</div>

@endsection


@section('script')
    <!-- DataTables -->
    <script type="text/javascript" src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script> 
    <script>
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });

        $(() => {
            $('a').removeClass('invisible')
        })
        
    </script>
    @include('partials.script-delete', ['text' => __('Vraiment supprimer cette role ?'), 'return' => 'removeTr'])
@endsection