routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([],function(){
	Route::get('eglise.log', 'HomeController@log')->name('eglise.log');
	Route::get('android', 'HomeController@download')->name('apk');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::group(['middleware'=>'auth:eglise', 'namespace'=>'Admin'], function(){

	Route::get('/', 'AdminController@index');
	Route::resource('groupe', 'GroupeController');
	Route::resource('annonce', 'AnnonceController');
	Route::put('annonce.state/{id}', 'AnnonceController@changeState')->name('annonce.state');
});

Route::group(['namespace'=>'Admin'], function(){
	Route::post('admin/log', 'AdminController@logAdmin')->name('admin.log');
});

Route::group(['middleware'=>'auth', 'namespace'=>'Admin'], function(){
		Route::get('admin', 'AdminController@index')->name('admin.index');
	  Route::resource('eglise', 'EgliseController');
});

Route::group(['middleware'=>'auth'], function(){
	Route::resource('district', 'District\DistrictController');
});

Route::resource('users', 'Users\UsersController');

Route::resource('roles', 'Users\RolesController');

Route::resource('permissions', 'Users\PermissionsController');

app/Models/Annonce.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\ {
        Iteration,
        Classe,
        Ecossa,
        Laic,
        Cult,
        Reunion,
        Diacre,
        Jeunesse,
        Musique,
        Divers,
        Ancienna,
        Annonce,
        Groupe,
    };

class Annonce extends Model
{
	private $data;



    protected $fillable = [
    	'pour_le', 'pense', 'eglise_id','statut'
    ];

    
}

app/Http/Controllers/API/AnnonceController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Requests\AllRequest;
use Carbon\Carbon;
use App\Http\Controllers\Controller;
use App\Models\ {
        Alert,
        Iteration,
        Classe,
        Ecossa,
        Etude,
        Laic,
        Cult,
        Reunion,
        Diacre,
        Jeunesse,
        Musique,
        Divers,
        Ancienna,
        Annonce,
        Groupe,
        Distrie,
        Eglise,
    };

class AnnonceController extends Controller
{
    private $alerts = [];

    public function getAnnonceByDate($from, $to)
    {

    	$models = ["Classe","Anciennat","Diaconat","Ecosa","Laic","Culte","Jeunesse","Musique","Reunion","Divers","Groupe","Etudes"];

        $annonces = [];
        
        $values = Annonce::whereBetween('pour_le', [$from, $to])->get();

        foreach ($values as $key => $value) {
            
            $annonces[$key] = $value;

            $annonces[$key]->data = json_encode($this->getData($models, $value->pour_le), true);

        }

        $result = [
            'status'=> 200,
            'annonces'=> $annonces,
            'alerts'=> $this->alerts
        ];

        return response()->json($result);
    }

    private function getData($models, $date)
    {
        $from = Carbon::parse($date);
        $limit = Carbon::parse($date);
        $from->subDay(6);
        $data = [];
        $temp = '';

        foreach ($models as $key => $model) {
            if($model === "Classe" || $model === "Groupe"){
                $model1 = "App\Models\\".$model;
                $data[$model] = $model1::all();                
            }else{
                $model1 = "App\Models\\".$model;
                $data[$model] = $model1::whereBetween('pour_le', [$from, $limit])->orderBy('pour_le')->get();
                
            }

            if(empty($data[$model]))
                unset($data[$model]);
            
            $nbre;
            
            $temp = json_encode($data[$model], true);

            str_replace(\Auth::user()->nom_complet, \Auth::user()->nom_complet, $temp, $nbre);

            if($nbre > 0){
                $this->alerts[] = [
                    'date_n'=> ''.$date,
                    'departement'=>$model,
                    'statut'=> '1',
                    'message'=> 'Vous faites partie des personnes ayant pour la semaine une tache a accomplir dans la vigne du Seigneur',
                ];
                
            }
            
        }

        return $data;

    }

    public function save(AllRequest $request)
    {
        $jours = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];
         
        if(!empty($request->get('model'))){
                   
            $class = 'App\Models\\'.ucfirst($request->get('model'));

            $tab = new $class();

            $fil = $tab->getFillable();

            $data = [];

            //return \Response::json($request->all(), 422);

            foreach ($fil as $value) {

                if($value =='eglise_id')
                    $data[$value] = (int)$request->get($value);
                else if($value == 'classe_id'){

                    if(is_null(Classe::where('ministere', $request->get('classe_id'))->get()->first())){
                
                        $temp = Classe::all();

                        $resp = 'Nom disponible: ';
                        
                        foreach ($temp as $key => $value) {
                           $resp .= $value->ministere.' ,';
                        }

                        $reponse = ['message'=> $resp];

                        return \Response::json($reponse, 422);

                    }

                    $data[$value] = Classe::where('ministere', $request->get($value))->get()->first()->id;
                
                }else if($value == 'groupe'){
                    
                    if(is_null(Groupe::where('nom', $request->get('groupe'))->get()->first())){
                    
                        $reponse = ['message'=> "ce groupe n'existe pas"];
                    
                        return \Response::json($reponse, 422);
                    
                    }
                    
                    $data[$value] = Groupe::where('nom', $request->get($value))->get()->first()->id;
                
                }else if($value == 'jour')
                    $data[$value] = (array_search(ucfirst($request->get('jour')), $jours) + 1);              
                else
                    $data[$value] = $request->get($value);
            }

            $class::create($data);

            if(strtolower($request->get('model')) == 'annonce')

            $reponse = ['code'=> '200', 'message'=> 'insertion reussie'];

            return \Response::json($reponse);       
        }else
            return \Response::json(['msg'=> 'Le model n\'est pa renseigne dans cette requette', 500]);
    }

    public function update(AllRequest $request, $id)
    {

        $jours = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];

        $classe_id = !empty($request->get('classe_id')) ? Classe::where('ministere', $request->get('classe_id'))->get()->first()->id : 1;

        $jour = !empty($request->get('jour')) ? $request->get('jour') : 0;

        $club = !empty($request->get('club')) ? $request->get('club') : 'Aventurier';

        if(!empty($request->get('model'))){
                   
            $model = 'App\Models\\'.ucfirst($request->get('model'));

            $temp=[];

            $instance = strtolower($request->get('model'));

            switch ($instance) {
                case 'ecosa':
                    $data = $request->all();
                    $data['classe_id'] = $classe_id;
                    $temp = $model::where('id', $id)
                    ->where('classe_id', $classe_id)->get()->first();
                    //return \Response::json(['message'=> $temp], 200);
                    $temp->update($data);
                    break;
                case 'laic':
                    $data = $request->all();
                    $data['classe_id'] = $classe_id;
                    $temp = $model::where('id', $id)
                    ->where('classe_id', $classe_id)->get()->first();
                    $temp->update($data);
                    break;
                case 'culte':
                    $data = $request->all();
                    $data['classe_id'] = $classe_id;
                    $temp = $model::where('id', $id)
                    ->where('classe_id', $classe_id)->get()->first();
                    $temp->update($data);
                    break;
                case 'anciennat':
                    $temp = $model::where('id', $id)->get()->first();
                    $temp->update($request->all());
                    break;
                case 'musique':
                    $temp = $model::where('id', $id)->get()->first();
                    $temp->update($request->all());                    
                    break;
                case 'reunion':
                    $temp = $model::where('id', $id)->get()->first();
                    $data = $request->all();
                    $data['jour'] = (array_search(ucfirst(strtolower($jour)), $jours) + 1);
                    //return \Response::json(['message'=> $data], 200);
                    $temp->update($data);
                case 'diaconat':
                    $temp = $model::where('id', $id)->get()->first();
                    $data = $request->all();
                    $data['jour'] = (array_search(ucfirst(strtolower($jour)), $jours) + 1);
                    //return \Response::json(['message'=> $data], 200);
                    $temp->update($data);
                    break;
                case 'etudes':
                    $temp = $model::where('id', $id)->get()->first();
                    $data = $request->all();
                    $data['jour'] = (array_search(ucfirst(strtolower($jour)), $jours) + 1);
                    $temp->update($data);
                    break;
                case 'jeunesse':
                    $temp = $model::where('id', $id)->get()->first();
                    $temp->update($request->all());
                    break;
                case 'divers':
                    $temp = $model::where('id', $id)->get()->first();
                    $temp->update($request->all());
                    break;
                case 'annonce':
                    $annonce = Annonce::findOrFail($id)->first();
                    $annonce->statut = 0;
                    $annonce->pense = $request->get('pense');
                    $annonce->pour_le = $request->get('pour_le');
                    $annonce->save();
                    Iteration::where('id', $id)->update(['status'=> '0', 'changed'=> '1']);
                    break;
                default:
                    Iteration::where('pour_le', $pour_le)->update(['changed'=> '0']);
                    $reponse = ['status'=> '200', 'msg'=> 'Departement '.$instance.'non retrouver'];
                    return \Response::json($reponse, 402);
                    break;
            }

            $annonce = Annonce::where('state', 'active')->get()->first();

            Iteration::where('eglise_id', $annonce->eglise_id)
                ->where('pour_le', $annonce->pour_le)
                ->get()
                ->last()
                ->update([
                    'changed'=> '0'
                ]);

            $annonce->statut = 0;

            $annonce->save();
            
            $reponse = ['message'=> 'Modification reussie', 'data'=>$temp];

            return \Response::json($reponse, 200);   
            
        }else
            return \Response::json(['status'=> '404', 'message'=>'Departement non retrouver', 'request'=> $request->all()], 404);

    }

    public function listPublish()
    {

resources/views/annonce/create.blade.php
@extends('layouts.form')


@section('card-0')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Penser de la semaine')
        @endslot

        @section('champs')
            {{ csrf_field() }}            
            @include('partials.form-area', [
                'title' => __('Penser de la semaine'),
                'type' => 'text',
                'name' => 'pense',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'annonce',
                ])
        @overwrite
    @endcomponent
@overwrite

@section('card-1')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Ecossa')
        @endslot

        @section('champs')
            {{ csrf_field() }}
            @include('partials.select-class',[
                'title'=> __('Eglise'),
                'name'=> 'classe_id',
                'options'=> $classes,
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Directeur'),
                'type' => 'text',
                'name' => 'directeur',
                'place' => 'Directeur-(trice)',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Priere'),
                'type' => 'text',
                'name' => 'priere',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Rapport'),
                'type' => 'text',
                'name' => 'rapport',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('5minute'),
                'type' => 'text',
                'name' => 'meditation',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Bulletin'),
                'type' => 'text',
                'name' => 'bulletin',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'ecossa',
                ])
        @overwrite
    @endcomponent            
@overwrite

@section('card-4')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Laic')
        @endslot

        @section('champs')
            {{ csrf_field() }}

            @include('partials.select-class',[
                'title'=> __('Eglise'),
                'name'=> 'classe_id',
                'options'=> $classes,
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Dierecteur'),
                'type' => 'text',
                'place' => 'Directeur-(trice)',
                'name' => 'directeur',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Rapport'),
                'type' => 'text',
                'name' => 'rapport',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'laic',
                ])
        @overwrite
    @endcomponent            
@overwrite

@section('card-3')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Cult')
        @endslot

        @section('champs')
            {{ csrf_field() }}

            @include('partials.select-class',[
                'title'=> __('Eglise'),
                'name'=> 'classe_id',
                'options'=> $classes,
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Bienvenue'),
                'type' => 'text',
                'name' => 'bienvenue',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Appelle'),
                'type' => 'text',
                'name' => 'appelle',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Lecture'),
                'type' => 'text',
                'name' => 'lecture',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Priere'),
                'type' => 'text',
                'name' => 'priere',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Service'),
                'type' => 'text',
                'place' => 'Service de fidelite',
                'name' => 'service',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Sermont'),
                'type' => 'text',
                'name' => 'predication',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Remerciment'),
                'type' => 'text',
                'name' => 'remerciment',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'cult',
                ])
        @overwrite
    @endcomponent
@overwrite       

@section('card-2')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Siegant pour la semaine')
        @endslot

        @section('champs')
            {{ csrf_field() }}

            @include('partials.select-days', [
                'title' => __('Jour'),
                'name' => 'jour',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Bienvenue'),
                'type' => 'text',
                'name' => 'bienvenue',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Remerciment'),
                'type' => 'text',
                'name' => 'remerciment',
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Predication'),
                'type' => 'text',
                'name' => 'meditation',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'reunion',
                ])
        @overwrite
    @endcomponent
@overwrite

@section('card-5')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Diaconna')
        @endslot

        @section('champs')
            {{ csrf_field() }}
            
            @include('partials.select-groupe', [
                'title' => __('Groupe'),
                'name' => 'groupe',
                'groupes' => $diaconna,
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'diacre',
                ])
        @overwrite
    @endcomponent
@overwrite

@section('card-6')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Jeunesse')
        @endslot

        @section('champs')
            {{ csrf_field() }}

            @include('partials.select-list', [
                'title' => __('Club'),
                'name' => 'club',
                'options' => ['Aventurier', 'Eclaireur', 'Segnor'],
                'required' => true,
                ])
            @include('partials.form-area', [
                'title' => __('Annonce'),
                'type' => 'text',
                'name' => 'info',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'jeunesse',
                ])            
        @overwrite
    @endcomponent
@overwrite

@section('card-7')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Musique')
        @endslot

        @section('champs')
            {{ csrf_field() }}

            @include('partials.select-groupe', [
                'title' => __('Groupe'),
                'name' => 'groupe',
                'groupes' => $musique,
                'required' => true,
                ])
            @include('partials.form-group', [
                'title' => __('Chant speciaux'),
                'type' => 'text',
                'name' => 'chant_special',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'musique',
                ])           
        @overwrite
    @endcomponent
@overwrite

@section('card-8')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Annonce divers')
        @endslot

        @section('champs')
            {{ csrf_field() }}

            @include('partials.select-list', [
                'title' => __('Departement'),
                'name' => 'departement',
                'options' => ["ancienna", "diacre", "ecossa", "laic", "cult", "jeunesse", "divers",
                                 "publication","famille","dorcas","education","fanm"],
                'required' => true,
                ])
            @include('partials.form-area', [
                'title' => __('Annonce'),
                'type' => 'text',
                'name' => 'info',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'divers',
                ])
        @overwrite
    @endcomponent
@overwrite

@section('card-9')

    @component('components.annonce', ['route' => route('annonce.store')])

        @slot('titre')
            @lang('Ancienna')
        @endslot

        @section('champs')
            {{ csrf_field() }}
            @include('partials.form-area', [
                'title' => __('Ancien'),
                'type' => 'text',
                'place' => 'Ancien de service pour la semaine',
                'name' => 'liste',
                'required' => true,
                ])
            @include('partials.hidden', [
                'value' => 'ancienna',
                ])
        @overwrite
    @endcomponent
@overwrite

resources/views/annonce/index.blade.php
@extends('layouts.app')
  @section('main')
    <ul class="breadcrumb">
        <li><a href="{{ route('admin.index') }}">Dashboard</a></li>
        <li><a href="{{ route('annonce.index') }}">Annonce</a></li>
        <li><a href="#" class="active">Afficher</a></li>
    </ul>
    <div class="row">
      <div class="col-md-12">
        <!-- START DEFAULT DATATABLE -->
        <div class="panel panel-default">
          <div class="panel-heading">                                
              <h3 class="panel-title">Liste des annonces</h3>
              <ul class="panel-controls">
                  <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                  <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                  <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
              </ul>                                
          </div>
          <div class="panel-body">
            <div class="table-responsive">
              <table class="table table-bordered table-striped datatable">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Statut</th>
                    <th>Penser</th>
                    <th>Consulter</th>
                    <th>Modifier</th>
                    <th>Supprimer</th>
                  </tr>
                </thead>
                <tbody>          
                  @foreach($annonces as $annonce)
                  <tr>
                    <td>{{ $annonce->id }}</td>
                    <td>{{ $annonce->pour_le }}</td>                                   
                    <td>
                      <form class="horizontal-form" action="{{ route('annonce.state', $annonce) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <input type="hidden" name="statut_update" value="{{ $annonce->statut }}">
                        <div class="form-group">
                          <button class="form-control btn btn-{{ $annonce->statut ? 'success' : 'warning' }}">{{ $annonce->statut ? 'disponible' : 'non-disponible' }}</button>
                        </div>                
                      </form>
                    </td>                  
                    <td>{{ $annonce->pense }}</td>                  
                    <td><a href="{{ route('annonce.show', $annonce) }}" class="btn btn-info form-control">Consulter</a></td>                  
                    <td>
                      <form class="horizontal-form" action="{{ route('annonce.edit', $annonce) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('GET') }}
                        <div class="form-group">
                          <button class="form-control btn btn-warning">@lang('Modifier')</button>
                        </div>                
                      </form>
                    </td>
                    <td>
                      <form class="horizontal-form" action="{{ route('annonce.destroy', $annonce->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <div class="form-group">
                          <button class="form-control btn btn-danger">@lang('Supprimer')</button>
                        </div>                
                      </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    @section('script')
      <script type='text/javascript' src="{{ asset('js/plugins/icheck/icheck.min.js') }} "></script>
      <script type="text/javascript" src="{{ asset('js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js') }} "></script>
      <script type="text/javascript" src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script> 
    @endsection
  @endsection
 

resources/views/annonce/show.blade.php
@extends('layouts.app')
  @section('content')
    <div class="container">
      <h4>La liste des eglises qui sont enregistres</h4>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Adresse</th>
            <th>Responsable</th>
            <th>Statut</th>
            <th>Avatar</th>
            <th>Modifier</th>
            <th>Supprimer</th>
          </tr>
        </thead>
        <tbody>          
          @foreach($eglises as $eglise)
          <tr>
            <td>{{$eglise['id']}}</td>
            <td>{{$eglise['nom']}}</td>
            <td>{{$eglise['adresse']}}</td>
            <td>{{$eglise['responsable']}}</td>
            <td>{{$eglise['statut']}}</td>
            <td>{{$eglise['avatar']}}</td>            
            <td><a href="{{ route('eglise.edit', $eglise) }}" class="btn btn-warning">Modifier</a></td>
            <td><a href="{{ route('eglise.destroy', $eglise) }}" class="btn btn-danger">Supprimer</td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  @endsection
 

resources/views/annonce/signal.blade.php
@extends('layouts.form')

@section('card')

    @component('components.card')

        @slot('title')
            @lang('Signalé une église non existante')
        @endslot

        <form method="POST" action="">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="form-group">
                <label for="category_id">@lang('Signalé cette église')</label>
                <select id="category_id" name="category_id" class="form-control">
                    @foreach($eglises as $eglise)
                        <option value="{{ $eglise->id }}">{{ $eglise->nom .' de '. $eglise->adresse }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="ok" name="ok" required>
                    <label class="custom-control-label" for="ok"> @lang('Je confirme que cette église n\'existe pas.')</label>
                </div>
            </div>
            @component('components.button', ['color'=>'warning'])
                @lang('Envoyer')

            @endcomponent
        </form>

    @endcomponent            

@endsection