routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([],function(){
	Route::get('eglise.log', 'HomeController@log')->name('eglise.log');
	Route::get('android', 'HomeController@download')->name('apk');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::group(['middleware'=>'auth:eglise', 'namespace'=>'Admin'], function(){

	Route::get('/', 'AdminController@index');
	Route::resource('groupe', 'GroupeController');
	Route::resource('annonce', 'AnnonceController');
	Route::put('annonce.state/{id}', 'AnnonceController@changeState')->name('annonce.state');
});

Route::group(['namespace'=>'Admin'], function(){
	Route::post('admin/log', 'AdminController@logAdmin')->name('admin.log');
});

Route::group(['middleware'=>'auth', 'namespace'=>'Admin'], function(){
		Route::get('admin', 'AdminController@index')->name('admin.index');
	  Route::resource('eglise', 'EgliseController');
});

Route::group(['middleware'=>'auth'], function(){
	Route::resource('district', 'District\DistrictController');
});

Route::resource('users', 'Users\UsersController');

Route::resource('roles', 'Users\RolesController');

Route::resource('permissions', 'Users\PermissionsController');

app/Http/Controllers/Users/PermissionsController.php
<?php

namespace App\Http\Controllers\Users;

Use \Auth;
use \Session;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;


class PermissionsController extends Controller
{
    public function __construct() {
        //$this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index() {
        
        $permissions = Permission::all(); //Get all permissions

        return view('admin.permissions.index')->with('permissions', $permissions);
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create() {
        
        $roles = Role::get(); //Get all roles

        return view('admin.permissions.create')->with('roles', $roles);
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request) {
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        Permission::create($request->only('name'));
        
        return redirect()->route('admin.permissions.index')
            ->with('flash_message',
             'Permission'. $permission->name.' added!');

    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id) {
        return redirect('permissions');
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id) {
        $permission = Permission::findOrFail($id);

        return view('admin.permissions.edit', compact('permission'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id) {
        $permission = Permission::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);
        $input = $request->all();
        $permission->fill($input)->save();

        return redirect()->route('admin.permissions.index')
            ->with('flash_message',
             'Permission'. $permission->name.' updated!');

    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id) {
        $permission = Permission::findOrFail($id);

    //Make it impossible to delete this specific permission    
    if ($permission->name == "administrateur") {
            return redirect()->route('admin.permissions.index')
            ->with('flash_message',
             'Cannot delete this Permission!');
        }

        $permission->delete();

        return response()->json();

    }

}

resources/views/admin/permissions/create.blade.php
{{-- \resources\views\permissions\create.blade.php --}}
@extends('layouts.app')

@section('title', '| Create Permission')

@section('content')
<div class="row">
    <div class="offset-md-3 mt-4 col-md-6">
        <!-- Horizontal Form -->
        <div class="card card-info">
            <div class="card-header">
                <h1 class="card-title"><i class='fa fa-key'></i> Add Permission</h1>
            </div>
            <div class="card-body">
                <br>
                {{ Form::open(array('url' => 'permissions')) }}

                <div class="form-group">
                    {{ Form::label('name', 'Name') }}
                    {{ Form::text('name', '', array('class' => 'form-control')) }}
                </div>               
                {{ Form::submit('Ajouter permission', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/permissions/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Permission')

@section('content')
<div class="row">
    <div class="offset-md-3 mt-4 col-md-6">
        <!-- Horizontal Form -->
        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title"><i class='fa fa-key'></i> Edit Role: {{$permission->name}}</h3>
            </div>
            <div class="card-body">
                {{ Form::model($permission, array('route' => array('permissions.update', $permission->id), 'method' => 'PUT')) }}{{-- Form model binding to automatically populate our fields with permission data --}}

                <div class="form-group">
                    {{ Form::label('name', 'Permission Name') }}
                    {{ Form::text('name', null, array('class' => 'form-control')) }}
                </div>
                <br>
                {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/permissions/index.blade.php
{{-- \resources\views\permissions\index.blade.php --}}
@extends('layouts.app')

@section('title', '| Permissions')


@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
@endsection


@section('content')

<div class="col-lg-8 offset-lg-2 mb-5">
    <h1><i class="fa fa-key"></i>Available Permissions

    <a href="{{ route('users.index') }}" class="btn btn-default pull-right">Users</a>
    <a href="{{ route('roles.index') }}" class="btn btn-default pull-right">Roles</a></h1>
    <hr>
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Data Table With Full Features</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="permissions" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Permissions</th>
                        <th>Operation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($permissions as $permission)
                    <tr>
                        <td>{{ $permission->name }}</td> 
                        <td>
                        <a href="{{ route('permissions.edit', $permission->id) }}" class="btn btn-info btn-sm pull-left mr-3 invisible" title="@lang('Modifier permission') {{$permission->name}}"><i class="fa fa-edit"></i> edite</a>
                        <a href="{{ route('permissions.destroy', $permission->id) }}" class="btn btn-danger btn-sm invisible" title="@lang('Supprimer permission') {{$permission->name}}">
                            <i class="fa fa-trash fa-lg"></i> supprime</a>  

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <a href="{{ URL::to('permissions/create') }}" class="btn btn-success">Add Permission</a>

</div>

@endsection

@section('scripts')
    <!-- DataTables -->
    <script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
    <script>
        $('#permissions').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": true,
            "ordering": true,
            "info": true,
            "autoWidth": false
        });

        $(() => {
            $('a').removeClass('invisible')
        })
        
    </script>
    @include('partials.script-delete', ['text' => __('Vraiment supprimer cette permission ?'), 'return' => 'removeTr'])
@endsection