routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([],function(){
	Route::get('eglise.log', 'HomeController@log')->name('eglise.log');
	Route::get('android', 'HomeController@download')->name('apk');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::group(['middleware'=>'auth:eglise', 'namespace'=>'Admin'], function(){

	Route::get('/', 'AdminController@index');
	Route::resource('groupe', 'GroupeController');
	Route::resource('annonce', 'AnnonceController');
	Route::put('annonce.state/{id}', 'AnnonceController@changeState')->name('annonce.state');
});

Route::group(['namespace'=>'Admin'], function(){
	Route::post('admin/log', 'AdminController@logAdmin')->name('admin.log');
});

Route::group(['middleware'=>'auth', 'namespace'=>'Admin'], function(){
		Route::get('admin', 'AdminController@index')->name('admin.index');
	  Route::resource('eglise', 'EgliseController');
});

Route::group(['middleware'=>'auth'], function(){
	Route::resource('district', 'District\DistrictController');
});

Route::resource('users', 'Users\UsersController');

Route::resource('roles', 'Users\RolesController');

Route::resource('permissions', 'Users\PermissionsController');

app/Models/Groupe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Groupe extends Model
{
    protected $fillable = [
    	'nom', 'departement', 'liste'
    ];
}

app/Http/Controllers/Admin/GroupeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Groupe;

class GroupeController extends Controller
{
       /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groupes = Groupe::all();

        return view('groupe.index')->withGroupes($groupes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('groupe.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'departement'=> 'required|string',
            'nom'=> 'required|string',
            'liste'=> 'required|string',
        ]);

        $data = $request->only('departement', 'nom', 'liste');

        Groupe::create($data);

        return redirect()->route('groupe.index')->with('ok', __("Le nouveu groupe est disponible pour le departement $request->departement"));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $groupe = Groupe::find($id);

        return view('groupe.show')->withGroupe($groupe);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $groupe = Groupe::find($id);

        return view('groupe.edit')->withGroupe($groupe);        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $groupe = Groupe::find($id);

        if($groupe->id == $request->get('variation'))
        {
            $groupe->update($request->only('nom', 'departement', 'liste'));

            return redirect()->route('groupe.index')->with('ok', __('La mise a jour est effectue avec succes'));
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $groupe = Groupe::find($id);

        $groupe->delete();

        return redirect()->route('groupe.index')->with('ok', __('Le groupe est supprime avec succes'));
    }
}

resources/views/groupe/create.blade.php
@extends('layouts.form')
    @section('main')
        <ul class="breadcrumb">
            <li><a href="{{ route('admin.index') }}">Home</a></li>
            <li><a href="{{ route('eglise.index') }}">Eglise</a></li>
            <li><a href="#">Nouveau groupe</a></li>
        </ul>
        @component('components.register', [
            'route' => route('groupe.store')])
            @slot('titre1')
                @lang('Ajouter un groupe')
            @endslot
            @slot('titre2')
                @lang('ici..')
            @endslot
            @section('champs')
                {{ csrf_field() }}
                @include('partials.select-list', [
                    'title' => __('Departement'),
                    'name' => 'departement',
                    'options' => ["ancienna", "diacre", "ecossa", "laic", "musique", "jeunesse",
                                     "publication","famille","dorcas","education","fanm"],
                    'required' => true,
                    ])
                @include('partials.form-group', [
                    'title' => __('Nom'),
                    'type' => 'text',
                    'name' => 'nom',
                    'place' => 'nom du groupe',                
                    'required' => true,
                    ])
                @include('partials.form-area', [
                    'title' => __('Liste des membres'),
                    'type' => 'text',
                    'name' => 'liste',
                    'required' => true,
                    ])
                @section('button')
                    @component('components.button')
                        @lang('Envoyer')
                    @endcomponent
                    @component('components.button',[
                        'type' => 'reset',
                        'color' => 'default',
                        'pull' => 'left'])
                        @lang('Effacer')
                    @endcomponent
                @endsection
            @endsection
        @endcomponent            
    @endsection

resources/views/groupe/edit.blade.php
@extends('layouts.form')
    @section('main')
        <ul class="breadcrumb">
            <li><a href="{{ route('admin.index') }}">Home</a></li>
            <li><a href="{{ route('eglise.index') }}">Eglise</a></li>
            <li><a href="#">Nouveau groupe</a></li>
        </ul>
        @component('components.register', [
            'route' => route('groupe.update', $groupe) ])
            @slot('titre1')
                @lang('Ajouter un groupe')
            @endslot
            @slot('titre2')
                @lang('ici..')
            @endslot
            @section('champs')
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                @include('partials.select-list', [
                    'title' => __('Departement'),
                    'name' => 'departement',
                    'value' => $groupe->departement,
                    'options' => ["ancienna", "diaconna", "ecossa", "laic", "musique", "jeunesse",
                                     "publication","famille","dorcas","education","fanm"],
                    'required' => true,
                    ])
                @include('partials.form-group', [
                    'title' => __('Nom'),
                    'type' => 'text',
                    'name' => 'nom',
                    'value' => $groupe->nom,
                    'place' => 'nom du groupe',                
                    'required' => true,
                    ])
                @include('partials.form-area', [
                    'title' => __('Liste des membres'),
                    'type' => 'text',
                    'name' => 'liste',
                    'value' => $groupe->liste,
                    'required' => true,
                    ])
                @include('partials.hidden', [
                    'name' => 'variation',
                    'value'=> $groupe->id
                    ])
                @section('button')
                    @component('components.button')
                        @lang('Envoyer')
                    @endcomponent
                    @component('components.button',[
                        'type' => 'reset',
                        'color' => 'default',
                        'pull' => 'left'])
                        @lang('Effacer')
                    @endcomponent
                @endsection
            @endsection
        @endcomponent            
    @endsection

resources/views/groupe/index.blade.php
@extends('layouts.app')
  @section('main')
  <ul class="breadcrumb">
      <li><a href="#">Home</a></li>                    
      <li><a href="#">Eglise</a></li>
      <li class="active">Liste eglise</li>
    </ul>
    <div class="row">
        <div class="col-md-12">
          <!-- START DEFAULT DATATABLE -->
          <div class="panel panel-default">
              <div class="panel-heading">                                
                <h3 class="panel-title">Liste des goupe enregistrer</h3>
                  <ul class="panel-controls">
                    <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
                      <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
                      <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
                  </ul>                                
              </div>
              <div class="panel-body">
              <table class="table table-bordered table-striped datatable">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Nom</th>
                  <th>departement</th>
                  <th>liste</th>
                  <th>Modifier</th>
                  <th>Supprimer</th>
                </tr>
              </thead>
              <tbody>          
                @foreach($groupes as $groupe)
                <tr>
                  <td>{{ $groupe->id }}</td>
                  <td>{{ $groupe->nom }}</td>
                  <td>{{ $groupe->departement }}</td>
                  <td>{{ $groupe->liste }}</td>
                  <td><a href="{{ route('groupe.edit', $groupe->id) }}" class="btn btn-warning">Modifier</a></td>
                  <td> @include('partials.form-delete', ['route'=> route('groupe.destroy', $groupe->id)])</td>
                </tr>
                @endforeach          
              </tbody>
            </table>
          </div>
          <div class="panel-footer">
            <a href="{{ route('groupe.create') }}" class="btn btn-success">Creer gourpe</a>            
          </div>
      </div>
    </div>
  </div>
    @section('script')
      <script type="text/javascript" src="{{ asset('js/plugins/datatables/jquery.dataTables.min.js') }}"></script> 
    @endsection
  @endsection
 

resources/views/groupe/show.blade.php
@extends('layouts.app')
  @section('content')
    <div class="container">
      <h4>La Distrie enregistrer est bien:</h4>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Adresse</th>
            <th>Responsable</th>
            <th>Statut</th>
            <th>Avatar</th>
            <th>Modifier</th>
            <th>Supprimer</th>
          </tr>
        </thead>
        <tbody>          
          <tr>
            <td>{{$distrie->id}}</td>
            <td>{{$distrie->nom}}</td>
            <td>{{$distrie->adresse}}</td>
            <td>{{$distrie->responsable}}</td>
            <td>{{$distrie->statut}}</td>
            <td>{{$distrie->avatar}}</td>            
            <td><a href="{{ route('distrie.edit', $distrie) }}" class="btn btn-warning">Modifier</a></td>
            <td><a href="{{ route('distrie.destroy', $distrie) }}" class="btn btn-danger">Supprimer</td>
          </tr>
        </tbody>
      </table>
    </div>
  @endsection
 

resources/views/groupe/signal.blade.php
@extends('layouts.form-center')

@section('card')

    @component('components.card')

        @slot('title')
            @lang('Signalé une église non existante')
        @endslot

        <form method="POST" action="">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="form-group">
                <label for="category_id">@lang('Signalé cette église')</label>
                <select id="category_id" name="category_id" class="form-control">
                    @foreach($eglises as $eglise)
                        <option value="{{ $eglise->id }}">{{ $eglise->nom .' de '. $eglise->adresse }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="ok" name="ok" required>
                    <label class="custom-control-label" for="ok"> @lang('Je confirme que cette église n\'existe pas.')</label>
                </div>
            </div>
            @component('components.button', ['color'=>'warning'])
                @lang('Envoyer')

            @endcomponent
        </form>

    @endcomponent            

@endsection